services:
  # PostgreSQL Database - Tenant A 
  db-tenant-a:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ancianato
      TZ: America/Bogota
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # PostgreSQL Database - Tenant B
  db-tenant-b:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ancianato_b
      TZ: America/Bogota
    ports:
      - "5433:5432"
    volumes:
      - pgdata_b:/var/lib/postgresql/data

  # PostgreSQL Database - Tenant C
  db-tenant-c:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ancianato_c
      TZ: America/Bogota
    ports:
      - "5434:5432"
    volumes:
      - pgdata_c:/var/lib/postgresql/data



  
  # MQTT Broker (Mosquitto) for IoT Wearables
  mosquitto:
    image: eclipse-mosquitto:2
    environment:
      TZ: America/Bogota
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  # Kafka using Kraft mode (no Zookeeper required)
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENERS=EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=EXTERNAL://localhost:9092,INTERNAL://kafka:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8083:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

volumes:
  pgdata:
  pgdata_b:
  pgdata_c:
  mosquitto_data:
  mosquitto_log:
